### ISSUE TITLE
Neovim support?

### ISSUE THREAD

**Issue by LinArcX** [axelf4/vim-snipp-snapp-snut-and-the-legend-continues#1]
Hi. seems interesting plugin. Is there any way to use it in neovim?

**Comment by Shougo** [comment]
I think it cannot.
I have read the code and it depends on Vim8.2 features.

**Comment by axelf4** [comment]
Indeed, it requires the `+textprop` feature. If it weren't for that I would support Neovim. Almost possible to emulate using extended marks if only they were allowed at `eol+1`.

Closing for now, will reopen if there's any development on the topic.
